%% Extract expanded cycle-level ML features from saved segmentation MAT files
% Input:
% - *_segments.mat files generated by batch_segment_all_trials.m
%
% Output:
% - cycle_features_for_ml_expanded.csv
% - cycle_features_for_ml_expanded.mat
% - fixed E0/H3 ML tables with random, trial-level, and subject-level splits
%
% Each row is one accepted gait cycle.
% Label for Classification Learner: braceLabel

clear; clc;

%% CONFIG
segmentsFolder = "C:\Users\2002s\OneDrive\Desktop\computer aided\segments_mat";
outputFolder = "C:\Users\2002s\OneDrive\Desktop\computer aided\_processed_segments_expanded";

if ~isfolder(segmentsFolder)
    selectedFolder = uigetdir(pwd, "Select folder containing *_segments.mat files");
    if isequal(selectedFolder, 0)
        error("No segments folder selected.");
    end
    segmentsFolder = string(selectedFolder);
end

if ~isfolder(outputFolder)
    mkdir(outputFolder);
end

featureCsv = fullfile(outputFolder, "cycle_features_for_ml_expanded.csv");
featureMat = fullfile(outputFolder, "cycle_features_for_ml_expanded.mat");

% Cadence is reported as steps/min. Because one segmented cycle is one
% right-foot stride, cadence = 2 steps per stride * 60 / stride duration.
cadenceMode = "steps_per_min";

% Fixed-condition ML table settings.
fixedIncline = 0;
fixedSpeed = 3;
testFraction = 0.30;
rngSeed = 519;

%% FIND SEGMENT FILES
files = dir(fullfile(segmentsFolder, "**", "*_segments.mat"));
if isempty(files)
    error("No *_segments.mat files found under: %s", segmentsFolder);
end

fprintf("Found %d segment MAT files.\n", numel(files));

allRows = cell(numel(files), 1);

for i = 1:numel(files)
    matFile = string(fullfile(files(i).folder, files(i).name));
    S = load(matFile, "result");
    result = S.result;

    allRows{i} = featuresFromOneResult(result, matFile, cadenceMode);
end

featureTable = vertcat(allRows{:});

writetable(featureTable, featureCsv);
save(featureMat, "featureTable");

fprintf("\nDone extracting expanded features.\n");
fprintf("Feature rows: %d cycles\n", height(featureTable));
fprintf("Feature CSV:  %s\n", featureCsv);
fprintf("Feature MAT:  %s\n", featureMat);

disp("Rows by brace label:");
disp(groupsummary(featureTable, "braceLabel"));

disp("Rows by speed/incline/brace:");
disp(groupsummary(featureTable, ["speedLevel", "inclineLevel", "braceLabel"]));

%% CREATE FIXED-CONDITION TABLES
fixedOutputFolder = fullfile(outputFolder, "fixed_E0_H3_ml_tables_expanded");
if ~isfolder(fixedOutputFolder)
    mkdir(fixedOutputFolder);
end

fixedMask = featureTable.inclineLevel == fixedIncline & featureTable.speedLevel == fixedSpeed;
Tf = featureTable(fixedMask, :);

if isempty(Tf)
    error("No rows found for inclineLevel=%g and speedLevel=%g.", fixedIncline, fixedSpeed);
end

fprintf("\nFixed E0/H3 expanded feature rows: %d cycles\n", height(Tf));
fprintf("Trials: %d\n", numel(unique(Tf.trialId)));
fprintf("Subjects: %d\n", numel(unique(Tf.subjectId)));

%% TABLE 1: FIXED E0/H3, NO CUSTOM SPLIT
T_random = addSplitColumn(Tf, "UseRandomSplitInClassificationLearner");

randomCsv = fullfile(fixedOutputFolder, ...
    "E0_H3_expanded_random_split_in_classification_learner.csv");
writetable(T_random, randomCsv);

%% TABLE 2: TRIAL-LEVEL SPLIT
rng(rngSeed);
T_trial = assignGroupSplit(Tf, "trialId", "braceLabel", testFraction);

trialCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_trial_level_split.csv");
trialTrainCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_trial_level_TRAIN.csv");
trialTestCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_trial_level_TEST.csv");

writetable(T_trial, trialCsv);
writetable(T_trial(T_trial.Split == "Train", :), trialTrainCsv);
writetable(T_trial(T_trial.Split == "Test", :), trialTestCsv);

%% TABLE 3: SUBJECT-LEVEL SPLIT
rng(rngSeed);
T_subject = assignSubjectSplit(Tf, testFraction);

subjectCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_subject_level_split.csv");
subjectTrainCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_subject_level_TRAIN.csv");
subjectTestCsv = fullfile(fixedOutputFolder, "E0_H3_expanded_subject_level_TEST.csv");

writetable(T_subject, subjectCsv);
writetable(T_subject(T_subject.Split == "Train", :), subjectTrainCsv);
writetable(T_subject(T_subject.Split == "Test", :), subjectTestCsv);

%% PREPARE CLASSIFICATION LEARNER TABLES
% Tables used directly in MATLAB Classification Learner.

% All data, no custom split
T_allData_noSplit = featureTable;

% Fixed E0/H3, no custom split
T_E0H3_noSplit = removevars(T_random, "Split");

% Fixed E0/H3, trial-level train-test split
T_E0H3_trial_train = removevars(T_trial(T_trial.Split == "Train", :), "Split");
T_E0H3_trial_test  = removevars(T_trial(T_trial.Split == "Test", :), "Split");

% Fixed E0/H3, subject-level train-test split
T_E0H3_subject_train = removevars(T_subject(T_subject.Split == "Train", :), "Split");
T_E0H3_subject_test  = removevars(T_subject(T_subject.Split == "Test", :), "Split");


%% SAVE SPLIT TABLES AS MAT
fixedTables.random = T_random;
fixedTables.trialLevel = T_trial;
fixedTables.subjectLevel = T_subject;

fixedTables.allDataNoSplit = T_allData_noSplit;
fixedTables.E0H3NoSplit = T_E0H3_noSplit;
fixedTables.E0H3TrialTrain = T_E0H3_trial_train;
fixedTables.E0H3TrialTest = T_E0H3_trial_test;
fixedTables.E0H3SubjectTrain = T_E0H3_subject_train;
fixedTables.E0H3SubjectTest = T_E0H3_subject_test;
splitMatFile = fullfile(fixedOutputFolder, "E0_H3_expanded_fixed_condition_tables.mat");
save(splitMatFile, "fixedTables");

fprintf("\nSaved expanded fixed E0/H3 ML tables:\n");
fprintf("Random/no split table: %s\n", randomCsv);
fprintf("Trial split table:     %s\n", trialCsv);
fprintf("Trial TRAIN table:     %s\n", trialTrainCsv);
fprintf("Trial TEST table:      %s\n", trialTestCsv);
fprintf("Subject split table:   %s\n", subjectCsv);
fprintf("Subject TRAIN table:   %s\n", subjectTrainCsv);
fprintf("Subject TEST table:    %s\n", subjectTestCsv);
fprintf("MAT file:              %s\n", splitMatFile);

fprintf("\nRandom table class counts:\n");
disp(groupsummary(T_random, "braceLabel"));

fprintf("Trial-level split counts:\n");
disp(groupsummary(T_trial, ["Split", "braceLabel"]));

fprintf("Subject-level split counts:\n");
disp(groupsummary(T_subject, ["Split", "braceLabel"]));

fprintf("Subject-level split subjects:\n");
disp(groupsummary(T_subject, ["Split", "subjectId"]));

%% LOCAL FUNCTIONS
function T = featuresFromOneResult(result, matFile, cadenceMode)
    cycles = result.flexCycles;
    nCycles = size(cycles, 2);

    if nCycles == 0
        T = table();
        return;
    end

    if isfield(result, "goodCycleMask") && numel(result.goodCycleMask) == numel(result.cycleDurSec)
        strideDuration = result.cycleDurSec(result.goodCycleMask);
    else
        strideDuration = result.cycleDurSec(:);
    end

    strideDuration = strideDuration(:);
    if numel(strideDuration) ~= nCycles
        n = min(numel(strideDuration), nCycles);
        cycles = cycles(:, 1:n);
        strideDuration = strideDuration(1:n);
        nCycles = n;
    end

    %% TIME-DOMAIN FEATURES
    maxFlexion = max(cycles, [], 1, "omitnan")';
    minFlexion = min(cycles, [], 1, "omitnan")';
    meanFlexion = mean(cycles, 1, "omitnan")';
    stdFlexion = std(cycles, 0, 1, "omitnan")';
    rmsFlexion = sqrt(mean(cycles.^2, 1, "omitnan"))';
    romFlexion = maxFlexion - minFlexion;

    if cadenceMode == "steps_per_min"
        cadence = 120 ./ strideDuration;
    else
        cadence = 60 ./ strideDuration;
    end

    %% FOURIER / HARMONIC FEATURES
    % These are extracted from time-normalized knee flexion cycles.
    % Therefore, they describe harmonic/shape content over 0-100% gait cycle,
    % not physical frequency in Hz.
    harmonicFeatures = harmonicFeaturesFromCycles(cycles);

    harmonic1Amp = harmonicFeatures.harmonic1Amp;
    harmonic2Amp = harmonicFeatures.harmonic2Amp;
    harmonic3Amp = harmonicFeatures.harmonic3Amp;
    spectralEnergy = harmonicFeatures.spectralEnergy;
    spectralEntropy = harmonicFeatures.spectralEntropy;
    lowHighHarmonicRatio = harmonicFeatures.lowHighHarmonicRatio;
    logLowHighHarmonicRatio = harmonicFeatures.logLowHighHarmonicRatio;

    %% LABELS AND METADATA
    condition = result.condition;
    braceLevel = repmat(condition.condD, nCycles, 1);
    inclineLevel = repmat(condition.condE, nCycles, 1);
    speedLevel = repmat(condition.condH, nCycles, 1);

    subjectId = repmat(string(result.subjectId), nCycles, 1);
    trialId = repmat(makeTrialId(result), nCycles, 1);
    sourceFile = repmat(string(result.sourceFile), nCycles, 1);
    segmentMatFile = repmat(string(matFile), nCycles, 1);
    cycleIndexInKeptSet = (1:nCycles)';

    if isfield(result, "goodCycleMask")
        keptOriginalIdx = find(result.goodCycleMask(:));
        if numel(keptOriginalIdx) >= nCycles
            cycleIndexOriginal = keptOriginalIdx(1:nCycles);
        else
            cycleIndexOriginal = nan(nCycles, 1);
        end
    else
        cycleIndexOriginal = (1:nCycles)';
    end

    T = table( ...
        subjectId, trialId, sourceFile, segmentMatFile, ...
        braceLevel, inclineLevel, speedLevel, ...
        categorical("D" + string(braceLevel)), ...
        categorical("E" + string(inclineLevel)), ...
        categorical("H" + string(speedLevel)), ...
        cycleIndexInKeptSet, cycleIndexOriginal, ...
        cadence, maxFlexion, strideDuration, romFlexion, ...
        meanFlexion, minFlexion, stdFlexion, rmsFlexion, ...
        harmonic1Amp, harmonic2Amp, harmonic3Amp, ...
        spectralEnergy, spectralEntropy, lowHighHarmonicRatio, ...
        logLowHighHarmonicRatio, ...
        'VariableNames', { ...
        'subjectId', 'trialId', 'sourceFile', 'segmentMatFile', ...
        'braceLevel', 'inclineLevel', 'speedLevel', ...
        'braceLabel', 'inclineLabel', 'speedLabel', ...
        'cycleIndexInKeptSet', 'cycleIndexOriginal', ...
        'cadence', 'maxFlexion', 'strideDuration', 'romFlexion', ...
        'meanFlexion', 'minFlexion', 'stdFlexion', 'rmsFlexion', ...
        'harmonic1Amp', 'harmonic2Amp', 'harmonic3Amp', ...
        'spectralEnergy', 'spectralEntropy', 'lowHighHarmonicRatio', ...
        'logLowHighHarmonicRatio'});
end

function H = harmonicFeaturesFromCycles(cycles)
    nCycles = size(cycles, 2);

    harmonic1Amp = nan(nCycles, 1);
    harmonic2Amp = nan(nCycles, 1);
    harmonic3Amp = nan(nCycles, 1);
    spectralEnergy = nan(nCycles, 1);
    spectralEntropy = nan(nCycles, 1);
    lowHighHarmonicRatio = nan(nCycles, 1);
    logLowHighHarmonicRatio = nan(nCycles, 1);

    for c = 1:nCycles
        x = cycles(:, c);
        x = double(x(:));

        if all(isnan(x))
            continue;
        end

        x = fillmissing(x, "linear", "EndValues", "nearest");

        % Remove duplicated 100% endpoint before FFT.
        if numel(x) > 2
            x = x(1:end-1);
        end

        % Remove mean before harmonic analysis.
        x = x - mean(x, "omitnan");

        N = numel(x);
        if N < 8
            continue;
        end

        Y = fft(x);

        % Single-sided amplitude spectrum, excluding DC.
        amp = abs(Y) ./ N;
        nHalf = floor(N / 2);
        ampSingle = 2 * amp(2:nHalf+1);

        powerSingle = ampSingle.^2;
        totalPower = sum(powerSingle, "omitnan");

        if numel(ampSingle) >= 1
            harmonic1Amp(c) = ampSingle(1);
        end
        if numel(ampSingle) >= 2
            harmonic2Amp(c) = ampSingle(2);
        end
        if numel(ampSingle) >= 3
            harmonic3Amp(c) = ampSingle(3);
        end

        spectralEnergy(c) = totalPower;

        if totalPower > 0
            p = powerSingle ./ totalPower;
            p = p(p > 0);
            spectralEntropy(c) = -sum(p .* log2(p)) ./ log2(numel(powerSingle));
        end

        lowIdx = 1:min(3, numel(powerSingle));
        highStart = 4;
        highEnd = min(10, numel(powerSingle));

        lowEnergy = sum(powerSingle(lowIdx), "omitnan");
        if highStart <= highEnd
            highEnergy = sum(powerSingle(highStart:highEnd), "omitnan");
        else
            highEnergy = nan;
        end

        lowHighHarmonicRatio(c) = lowEnergy ./ (highEnergy + eps);
        logLowHighHarmonicRatio(c) = log10(lowHighHarmonicRatio(c));
    end

    H = table( ...
        harmonic1Amp, harmonic2Amp, harmonic3Amp, ...
        spectralEnergy, spectralEntropy, lowHighHarmonicRatio, ...
        logLowHighHarmonicRatio);
end

function trialId = makeTrialId(result)
    conditionCode = string(result.condition.conditionCode);
    trialId = string(result.subjectId) + "_" + conditionCode;
end

function T = addSplitColumn(T, splitValue)
    T.Split = repmat(string(splitValue), height(T), 1);
    T = movevars(T, "Split", "After", "braceLabel");
end

function T = assignGroupSplit(T, groupVar, labelVar, testFraction)
    T.Split = repmat("Train", height(T), 1);
    labels = unique(T.(labelVar), "stable");

    for i = 1:numel(labels)
        label = labels(i);
        labelMask = T.(labelVar) == label;
        groups = unique(T.(groupVar)(labelMask), "stable");
        groups = groups(randperm(numel(groups)));

        nTestGroups = max(1, round(testFraction * numel(groups)));
        testGroups = groups(1:nTestGroups);

        T.Split(ismember(T.(groupVar), testGroups)) = "Test";
    end

    T.Split = categorical(T.Split);
    T = movevars(T, "Split", "After", "braceLabel");
end

function T = assignSubjectSplit(T, testFraction)
    T.Split = repmat("Train", height(T), 1);
    subjects = unique(T.subjectId, "stable");
    subjects = subjects(randperm(numel(subjects)));

    nTestSubjects = max(1, round(testFraction * numel(subjects)));
    testSubjects = subjects(1:nTestSubjects);

    T.Split(ismember(T.subjectId, testSubjects)) = "Test";
    T.Split = categorical(T.Split);
    T = movevars(T, "Split", "After", "braceLabel");
end
